[hostname]
ssh_only = false

[username]
show_always = true
format = '[$user](bold red) on '

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = 'python3'
detect_extensions = []
disabled = false

[character]
success_symbol = '[âœ”](bold green) '
error_symbol = '[âœ˜](bold red) '

[directory]
read_only = ' ðŸ”’'

[perl]
disabled = true

[vagrant]
disabled = true

# Increase command timeout to avoid git warnings on slow connections
command_timeout = 1000
